TEMPLATEROOT = ..

# compilation flags for gdb

CFLAGS  = -O1 -g
ASFLAGS = -g

# object files

OBJS =  $(STARTUP) main.o
OBJS += st7735.o spi.o libdelay.o font.o

# include common make file

include $(TEMPLATEROOT)/Makefile.common
