TEMPLATEROOT = ..

# compilation flags for gdb

CFLAGS  = -O1 -g
ASFLAGS = -g

# object files

OBJS =  $(STARTUP) main.o
OBJS += spi.o libdelay.o led.o

# include common make file

include $(TEMPLATEROOT)/Makefile.common
